In [1]:
import pandas as pd

In [2]:
df_examples = pd.read_parquet('shopping_queries_dataset_examples.parquet')
df_products = pd.read_parquet('shopping_queries_dataset_products.parquet')

In [3]:
df_examples

,example_id,query,query_id,product_id,product_locale,esci_label,small_version,large_version,split
0,0,revent 80 cfm,0,B000MOO21W,us,I,0,1,train
1,1,revent 80 cfm,0,B07X3Y6B1V,us,E,0,1,train
2,2,revent 80 cfm,0,B07WDM7MQQ,us,E,0,1,train
3,3,revent 80 cfm,0,B07RH6Z8KW,us,E,0,1,train
4,4,revent 80 cfm,0,B07QJ7WYFQ,us,E,0,1,train
...,...,...,...,...,...,...,...,...,...
2621283,2621283,�����j�[�h�p�[�x abrasus,130651,B0063ASUY4,jp,E,0,1,test
2621284,2621284,�����j�[�h�p�[�x abrasus,130651,B0062EZYIG,jp,E,0,1,test
2621285,2621285,�����j�[�h�p�[�x abrasus,130651,B07H8MWBZN,jp,S,0,1,test
2621286,2621286,�����j�[�h�p�[�x abrasus,130651,B00IZH4T9S,jp,E,0,1,test
2621287,2621287,�����j�[�h�p�[�x abrasus,130651,B07R536DG1,jp,E,0,1,test

In [4]:
df_products

,product_id,product_title,product_description,product_bullet_point,product_brand,product_color,product_locale
0,B079VKKJN7,"11 Degrees de los Hombres Playera con Logo, Ne...",Esta playera con el logo de la marca Carrier d...,11 Degrees Negro Playera con logo\nA estrenar ...,11 Degrees,Negro,es
1,B079Y9VRKS,Camiseta Eleven Degrees Core TS White (M),None,None,11 Degrees,Blanco,es
2,B07DP4LM9H,11 Degrees de los Hombres Core Pull Over Hoodi...,La sudadera con capucha Core Pull Over de 11 G...,11 Degrees Azul Core Pull Over Hoodie\nA estre...,11 Degrees,Azul,es
3,B07G37B9HP,11 Degrees Poli Panel Track Pant XL Black,None,None,11 Degrees,None,es
4,B07LCTGDHY,11 Degrees Gorra Trucker Negro OSFA (Talla úni...,None,None,11 Degrees,Negro (,es
...,...,...,...,...,...,...,...
1814919,B09FJYBVKS,スポーツブラ 揺れない ヨガウェア レディース トップス 通気性 ナイトブラ スポーツブラジ...,<p>【注意事項】</p><p>※商品内容以外のアクセサリー・小物等は付属しません.</p>...,シンプルのデザインで合わせやすいです。コート、半袖、シャツを合わせて、家で着てもいい、寝てい...,Doworspaw,ベージュ,jp
1814920,B09FTJ3S1N,ブラジャー レディース 補正ブラ Gabrioir 揺れない 大きいサイズ バストアップ美胸...,<p>【配送】</p><p>普通には2-3日後出荷できますが。出荷した後15-25日ぐらい届...,【いろんな場合に適用】軽い運動時、家事、外出、長時間移動、温泉旅行などに活用なセクシルームブ...,Gabrioir,パープル,jp
1814921,B09G72LDQZ,レディース ブラジャー 補正ブラ トップス Gabrioir 大きいサイズ 揺れない 脇高設...,<p>【配送】</p><p>普通には2-3日後出荷できますが。出荷した後15-25日ぐらい届...,【いろんな場合に適用】軽い運動時、家事、外出、長時間移動、温泉旅行などに活用なセクシルームブ...,Gabrioir,ベージュ,jp
1814922,B09GBGRTPB,ナイトブラ ノンワイヤーブラ ブラジャー レディース Gabrioir 大きいサイズ パット...,<p>【配送】</p><p>普通には2-3日後出荷できますが。出荷した後15-25日ぐらい届...,【いろんな場合に適用】軽い運動時、家事、外出、長時間移動、温泉旅行などに活用なセクシルームブ...,Gabrioir,パープル,jp
1814923,B09GBKN83Q,インナーキャミソール レディース ブラトップ キャミソール Gabrioir ノーワイヤー ...,<p>【配送】</p><p>普通には2-3日後出荷できますが。出荷した後15-25日ぐらい届...,【いろんな場合に適用】軽い運動時、家事、外出、長時間移動、温泉旅行などに活用なセクシルームブ...,Gabrioir,ブラック,jp

In [5]:
df_products['product_description'] = df_products['product_description'].fillna("")

In [6]:
df_examples_products = pd.merge(
        df_examples,
        df_products,
        how='left',
        left_on=['product_locale', 'product_id'],
        right_on=['product_locale', 'product_id']
    )

In [7]:
df_examples_products

,example_id,query,query_id,product_id,product_locale,esci_label,small_version,large_version,split,product_title,product_description,product_bullet_point,product_brand,product_color
0,0,revent 80 cfm,0,B000MOO21W,us,I,0,1,train,Panasonic FV-20VQ3 WhisperCeiling 190 CFM Ceil...,,WhisperCeiling fans feature a totally enclosed...,Panasonic,White
1,1,revent 80 cfm,0,B07X3Y6B1V,us,E,0,1,train,Homewerks 7141-80 Bathroom Fan Integrated LED ...,,OUTSTANDING PERFORMANCE: This Homewerk's bath ...,Homewerks,80 CFM
2,2,revent 80 cfm,0,B07WDM7MQQ,us,E,0,1,train,Homewerks 7140-80 Bathroom Fan Ceiling Mount E...,,OUTSTANDING PERFORMANCE: This Homewerk's bath ...,Homewerks,White
3,3,revent 80 cfm,0,B07RH6Z8KW,us,E,0,1,train,Delta Electronics RAD80L BreezRadiance 80 CFM ...,This pre-owned or refurbished product has been...,Quiet operation at 1.5 sones\nBuilt-in thermos...,DELTA ELECTRONICS (AMERICAS) LTD.,White
4,4,revent 80 cfm,0,B07QJ7WYFQ,us,E,0,1,train,Panasonic FV-08VRE2 Ventilation Fan with Reces...,,The design solution for Fan/light combinations...,Panasonic,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2621283,2621283,�����j�[�h�p�[�x abrasus,130651,B0063ASUY4,jp,E,0,1,test,薄い財布 abrAsus ブッテーロレザーエディション ブラック,2013年グッドデザイン賞受賞。<br/> 「薄い財布abrAsus」は、財布をゼロベースで...,イタリア産の上質なヌメ革を使用した最上級ブッテーロレザーエディション。\nグッドデザイン賞を...,abrAsus(アブラサス),ブラック
2621284,2621284,�����j�[�h�p�[�x abrasus,130651,B0062EZYIG,jp,E,0,1,test,アブラサス (abrAsus) 薄い財布 ブラック,グッドデザイン賞受賞。 <br /> 「薄い財布abrAsus」は、財布をゼロベースで考えた...,グッドデザイン賞を受賞しました。\n特別な構造（特許取得済み）で、圧倒的な薄さを実現しました...,abrAsus(アブラサス),ブラック
2621285,2621285,�����j�[�h�p�[�x abrasus,130651,B07H8MWBZN,jp,S,0,1,test,Bellroy Hide & Seek Wallet - スリムなレザー製二つ折り財布、RF...,<b>スリムな財布へ</b><br> ベルロイは、毎日の必需品をスマートに持ち運べる製品の開...,ポケットをフラットに保てるスリムなシルエットかつクラシックなデザイン\nRFID保護（スキミ...,Bellroy(ベルロイ),Black - RFID (New)
2621286,2621286,�����j�[�h�p�[�x abrasus,130651,B00IZH4T9S,jp,E,0,1,test,小さい小銭入れ abrAsus (アブラサス) ダークグリーン,<b>「コイン」「紙幣」「キー」だけを持ち運ぶ キーホルダーみたいな財布</b> <br> ...,「コイン」「紙幣」「キー」だけを一緒に持ち歩く、キーホルダーのような財布です。\n500円玉...,abrAsus(アブラサス),ダークグリーン
2621287,2621287,�����j�[�h�p�[�x abrasus,130651,B07R536DG1,jp,E,0,1,test,小さい財布 abrAsus アブラサス 最上級ブッテーロレザーエディション ブルー,手のひらやポケットにさっと収まるコンパクトサイズで、一般的な小さい財布より、ダントツに小さい...,手のひらやポケットに、さっと収まる快適さ。\n一般的な小さい財布より、ダントツに小さい極小財...,abrAsus(アブラサス),ブルー

In [8]:
set(df_examples_products.product_locale)

{'es', 'jp', 'us'}

In [9]:
df_examples_products.split.value_counts()

split
train    1983272
test      638016
Name: count, dtype: int64

In [10]:
del df_products
del df_examples

In [11]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

locale_le = LabelEncoder()
locale_le.fit(df_examples_products.product_locale)

LabelEncoder()

In [12]:
print(f"LabelEncoder classes: {locale_le.classes_}")

LabelEncoder classes: ['es' 'jp' 'us']

In [13]:
esci_le = LabelEncoder()
esci_le.fit(df_examples_products.esci_label)

LabelEncoder()

In [14]:
esci_label2relevance = {
        'E' : 3,
        'S' : 2,
        'C' : 1,
        'I' : 0,
    }

esci_label2gain = {
        'E' : 1,
        'S' : 0.1,
        'C' : 0.01,
        'I' : 0,
    }

### Pytorch DCN model for ESCI classification

In [15]:
from transformers import AutoTokenizer, AutoModel
import torch.nn as nn
import torch
from deepctr_torch.layers import CrossNet

c:\Users\lifen\anaconda3\envs\interview\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [16]:
import deepctr_torch
deepctr_torch.__version__

'0.2.9'

In [17]:
# class DNWithEmbeddings(nn.Module):
#     def __init__(
#             self, 
#             embedding_model_name, 
#             locale_le, 
#             num_text=6,
#             num_classes=4, 
#             locale_vocab_size=3, 
#             locale_emb_dim=8,
#             deep_hidden_dims: list = [512, 256, 128], # Dimensions of deep layers
#             dropout_rate: float = 0.2,
#             freeze_embedding_model: bool = True
#         ):
#         super().__init__()
#         self.tokenizer = AutoTokenizer.from_pretrained(embedding_model_name)
#         self.embedding_model = AutoModel.from_pretrained(embedding_model_name)
#         self.text_embedding_dim = self.embedding_model.config.hidden_size
#         if freeze_embedding_model:
#             for param in self.embedding_model.parameters():
#                 param.requires_grad = False
#             print(f"Frozen parameters of {embedding_model_name}")

#         self.locale_emb = nn.Embedding(locale_vocab_size, locale_emb_dim)
#         self.locale_le = locale_le
#         # self.cross = ... # your cross layers
#         total_input_dim = num_text * self.text_embedding_dim + locale_emb_dim
#         # deep layer
#         deep_layers = []
#         current_input_dim = total_input_dim
#         for hidden_dim in deep_hidden_dims:
#             deep_layers.append(nn.Linear(current_input_dim, hidden_dim))
#             deep_layers.append(nn.ReLU())
#             deep_layers.append(nn.Dropout(dropout_rate))
#             current_input_dim = hidden_dim
#         self.deep = nn.Sequential(*deep_layers)
#         self.classifier = nn.Linear(current_input_dim, num_classes)

#     def embed_text(self, texts):
#         # texts: list of strings
#         tokens = self.tokenizer(texts, padding=True, truncation=True, return_tensors='pt')
#         outputs = self.bert(**tokens)
#         # Use [CLS] token embedding
#         return outputs.last_hidden_state[:, 0, :]
    
#     def encode_locale(self, locale):
#         return torch.tensor(self.locale_le.transform(locale))

#     def forward(self, batch):
#         # batch: dict with keys for each field
#         query_emb = self.embed_text(batch['query'])
#         title_emb = self.embed_text(batch['product_title'])
#         desc_emb = self.embed_text(batch['product_description'])
#         bullet_emb = self.embed_text(batch['product_bullet_point'])
#         brand_emb = self.embed_text(batch['product_brand'])
#         color_emb = self.embed_text(batch['product_color'])
#         locale_emb = self.locale_emb(self.encode_locale(batch['product_locale']))
#         # Concatenate all embeddings
#         x = torch.cat([title_emb, desc_emb, bullet_emb, brand_emb, color_emb, locale_emb], dim=1)
#         # Pass through DN layers and classifier
#         x = self.deep(x)
#         logits = self.classifier(x)
#         return logits

In [18]:
from torch.utils.data import Dataset, DataLoader
class CustomDataset(Dataset):
    def __init__(
            self, data, 
            embedding_model_name="bert-base-cased", 
            locale_le=None,
            esci_le=None
        ):
        super().__init__()

        self.data_df = data
        self.tokenizer = AutoTokenizer.from_pretrained(embedding_model_name)
        self.embedding_model = AutoModel.from_pretrained(embedding_model_name)
        self.embedding_model.eval()
        for param in self.embedding_model.parameters():
            param.requires_grad = False
        print(f"BERT embedding model '{embedding_model_name}' loaded, frozen, and set to eval mode in Dataset.")

        self.locale_le = locale_le
        self.esci_le = esci_le

        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.embedding_model.to(self.device)

    def __len__(self):
        return len(self.data_df)
    
    def _get_text_embedding(self, texts):
        # print(f"Getting text embedding for: {texts}")
        if not texts:
            texts = ""
        if isinstance(texts, float) and np.isnan(texts):
            texts = ""
        if not isinstance(texts, list):
            texts = [texts]
        with torch.no_grad():
            tokens = self.tokenizer(texts, padding=True, truncation=True, return_tensors='pt')
            tokens = {k: v.to(self.device) for k, v in tokens.items()} # Move input tokens to the same device
            outputs = self.embedding_model(**tokens)
            return outputs.last_hidden_state[:, 0, :]


    def __getitem__(self, idx):
        item = self.data_df.iloc[idx]

        query = self._get_text_embedding(item['query']).squeeze(0)

        product_title = self._get_text_embedding(item['product_title']).squeeze(0)
        # print(f"Product title tensor: {product_title}")
        product_description = self._get_text_embedding(item['product_description']).squeeze(0)
        product_bullet_point = self._get_text_embedding(item['product_bullet_point']).squeeze(0)
        product_brand = self._get_text_embedding(item['product_brand']).squeeze(0)
        product_color = self._get_text_embedding(item['product_color']).squeeze(0)

        product_locale = self.locale_le.transform([item['product_locale']])
        # print(product_locale)
        product_locale = torch.tensor(product_locale, dtype=torch.long)
        # print(f"Product locale tensor: {product_locale}")

        esci_label = self.esci_le.transform([item['esci_label']])
        esci_label = torch.tensor(esci_label, dtype=torch.long)

        return {
            'query_embed': query,
            'product_title_embed': product_title,
            'product_description_embed': product_description,
            'product_bullet_point_embed': product_bullet_point,
            'product_brand_embed': product_brand,
            'product_color_embed': product_color,
            'product_locale': product_locale
        }, esci_label

In [19]:
class DCNWithEmbeddings(nn.Module):
    def __init__(
            self, 
            text_embedding_dim, 
            num_text=6,
            num_classes=4, 
            locale_vocab_size=3, 
            locale_emb_dim=8,
            deep_hidden_dims: list = [512, 256, 128], # Dimensions of deep layers
            dropout_rate: float = 0.2,
            apply_cross_net: bool = True,
            cross_net_type: str = 'parallel', # 'parallel' or 'stack'
            # freeze_embedding_model: bool = True
        ):
        super().__init__()

        self.text_embedding_dim = text_embedding_dim
        
        self.locale_emb = nn.Embedding(locale_vocab_size, locale_emb_dim)
        # self.cross = ... # your cross layers
        total_input_dim = num_text * self.text_embedding_dim + locale_emb_dim
        # deep layer
        deep_layers = []
        current_input_dim = total_input_dim
        for hidden_dim in deep_hidden_dims:
            deep_layers.append(nn.Linear(current_input_dim, hidden_dim))
            deep_layers.append(nn.ReLU())
            deep_layers.append(nn.Dropout(dropout_rate))
            current_input_dim = hidden_dim
        self.deep = nn.Sequential(*deep_layers)
        if apply_cross_net and cross_net_type == 'stack':
            self.cross_net = CrossNet(current_input_dim, layer_num=2, parameterization='vector')
        if apply_cross_net and cross_net_type == 'parallel':
            parallel_cross_net_input_dim = num_text * self.text_embedding_dim + locale_emb_dim
            self.cross_net = CrossNet(parallel_cross_net_input_dim, layer_num=2, parameterization='vector')
            self.parallel_cross_net_head = nn.Sequential(
                nn.Linear(parallel_cross_net_input_dim + deep_hidden_dims[-1], deep_hidden_dims[-1]),
                nn.ReLU(),
                nn.Dropout(dropout_rate)
            )

        self.classifier = nn.Linear(current_input_dim, num_classes)

        self.apply_cross_net = apply_cross_net
        self.cross_net_type = cross_net_type


    def forward(self, batch):
        # batch: dict with keys for each field
        query_emb = batch['query_embed']
        # print("Query embedding shape:", query_emb.shape)
        title_emb = batch['product_title_embed']
        # print("Title embedding shape:", title_emb.shape)
        desc_emb = batch['product_description_embed']
        # print("Description embedding shape:", desc_emb.shape)
        bullet_emb = batch['product_bullet_point_embed']
        # print("Bullet point embedding shape:", bullet_emb.shape)
        brand_emb = batch['product_brand_embed']
        # print("Brand embedding shape:", brand_emb.shape)
        color_emb = batch['product_color_embed']
        # print("Color embedding shape:", color_emb.shape)
        locale_emb = self.locale_emb(batch['product_locale'].squeeze(-1))
        # print("Product locale tensor shape:", batch['product_locale'].squeeze(-1).shape)
        # print("Locale embedding shape:", locale_emb.shape)
        # print("Locale embedding:", locale_emb)
        # Concatenate all embeddings
        x = torch.cat([query_emb, title_emb, desc_emb, bullet_emb, brand_emb, color_emb, locale_emb], dim=1)
        # Pass through DN layers and classifier
        if not self.apply_cross_net:
            x = self.deep(x)
            logits = self.classifier(x)
        if self.apply_cross_net and self.cross_net_type == 'stack':
            x = self.deep(x)
            x = self.cross_net(x)
            logits = self.classifier(x)
        if self.apply_cross_net and self.cross_net_type == 'parallel':
            deep_x = self.deep(x)
            cross_x = self.cross_net(x)
            x = torch.cat([deep_x, cross_x], dim=1)
            x = self.parallel_cross_net_head(x)
            logits = self.classifier(x)            

        
        return logits

In [20]:
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

NUM_CLASSES = len(esci_le.classes_) # Example: 4
LOCALE_VOCAB_SIZE = len(locale_le.classes_) # Example: 4
LOCALE_EMB_DIM = 8
TEXT_EMBEDDING_DIM = 768 # For bert-base-uncased
NUM_TEXT = 6
DEEP_HIDDEN_DIMS = [512, 256, 128]
DROPOUT_RATE = 0.2



model = DCNWithEmbeddings(
    text_embedding_dim = TEXT_EMBEDDING_DIM, 
    num_text = NUM_TEXT,
    num_classes = NUM_CLASSES, 
    locale_vocab_size = LOCALE_VOCAB_SIZE, 
    locale_emb_dim = LOCALE_EMB_DIM,
    deep_hidden_dims = DEEP_HIDDEN_DIMS, # Dimensions of deep layers
    dropout_rate = DROPOUT_RATE,
)

model.to(DEVICE)

model

DCNWithEmbeddings(
  (locale_emb): Embedding(3, 8)
  (deep): Sequential(
    (0): Linear(in_features=4616, out_features=512, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=512, out_features=256, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.2, inplace=False)
    (6): Linear(in_features=256, out_features=128, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.2, inplace=False)
  )
  (cross_net): CrossNet()
  (parallel_cross_net_head): Sequential(
    (0): Linear(in_features=4744, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
  )
  (classifier): Linear(in_features=128, out_features=4, bias=True)
)

In [21]:
train_dataset = CustomDataset(
    data=df_examples_products[df_examples_products['split'] == 'train'],
    locale_le=locale_le,
    esci_le=esci_le,
    embedding_model_name="bert-base-cased"
)
test_dataset = CustomDataset(
    data=df_examples_products[df_examples_products['split'] == 'test'],
    locale_le=locale_le,
    esci_le=esci_le,
    embedding_model_name="bert-base-cased" # Make sure to pass model name
)

train_dataloader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=0) # num_workers=0 for simplicity
test_dataloader = DataLoader(test_dataset, batch_size=16, shuffle=False, num_workers=0) # For GPU data transfer demo

BERT embedding model 'bert-base-cased' loaded, frozen, and set to eval mode in Dataset.
BERT embedding model 'bert-base-cased' loaded, frozen, and set to eval mode in Dataset.
BERT embedding model 'bert-base-cased' loaded, frozen, and set to eval mode in Dataset.

In [22]:
def count_trainable_params(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Trainable parameters: {count_trainable_params(model):,}")

Trainable parameters: 3,154,492

In [23]:
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()

In [24]:
print(f"\nTraining model on: {DEVICE}")
print("Starting training loop...")

Training model on: cuda
Starting training loop...

In [28]:
num_epochs = 1 # Try
for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    for batch_idx, (inputs, labels) in enumerate(train_dataloader):
        # terminate after 11 batches
        if batch_idx > 10:
            break

        # --- HERE IS WHERE YOU MOVE BATCH DATA TO GPU ---
        # `inputs` is the dictionary from your Dataset, `labels` is the target tensor
        
        # Move all tensors within the 'inputs' dictionary to the device
        for key in inputs:
            inputs[key] = inputs[key].to(DEVICE)
            # print(f"Device of {key}: {inputs[key].device}")

            
        # Move the labels tensor to the device
        labels = labels.squeeze(-1)  
        labels = labels.to(DEVICE)
        # ----------------------------------------------------

        # --- DEBUGGING LINES ---
        # print(inputs)
        # print(f"Device of locale_emb.weight: {model.locale_emb.weight.device}")

        optimizer.zero_grad()
        for key in inputs:
            inputs[key] = inputs[key].to(DEVICE)
            # print(f"Device of input: {inputs[key].device}")
        
        logits = model(inputs) # Pass the dictionary of tensors
        logits = logits.to(DEVICE)
        # print(f"Logits: {logits}, Labels: {labels}")
        # print(f"Logits shape: {logits.shape}, Labels shape: {labels.shape}")
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

        if batch_idx % 10 == 0:
            print(f"Epoch {epoch+1}, Batch {batch_idx}, Loss: {loss.item():.4f}")

    avg_train_loss = total_loss / len(train_dataloader)
    print(f"Epoch {epoch+1} finished. Average Train Loss: {avg_train_loss:.4f}")

    # (Optional) Validation loop
    model.eval()
    test_loss = 0
    with torch.no_grad():
        for i, (inputs, labels) in enumerate(test_dataloader):
            # terminate after 100 batches for test set
            if i > 11:
                break
            # Move validation data to GPU as well
            for key in inputs:
                inputs[key] = inputs[key].to(DEVICE)
            
            labels = labels.squeeze(-1)  
            labels = labels.to(DEVICE)

            logits = model(inputs)
            loss = criterion(logits, labels)
            test_loss += loss.item()

            if i % 10 == 0:
                print(f"Test set: Epoch {epoch+1}, Batch {i}, Loss: {loss.item():.4f}")

    avg_test_loss = test_loss / len(test_dataloader)
    print(f"Test set Loss: {avg_test_loss:.4f}")

print("Training complete!")

Epoch 1, Batch 0, Loss: 1.0513
Epoch 1, Batch 10, Loss: 0.8610
Epoch 1, Batch 10, Loss: 0.8610
Epoch 1 finished. Average Train Loss: 0.0001
Epoch 1 finished. Average Train Loss: 0.0001
Test set: Epoch 1, Batch 0, Loss: 1.6934
Test set: Epoch 1, Batch 0, Loss: 1.6934
Test set: Epoch 1, Batch 10, Loss: 0.4745
Test set: Epoch 1, Batch 10, Loss: 0.4745
Test set Loss: 0.0003
Training complete!
Test set Loss: 0.0003
Training complete!

### Evaluation metrics

In [ ]:
# ESCI classification
import torch
from sklearn.metrics import classification_report
import numpy as np

model.eval()
val_loss = 0
all_labels = []
all_predictions = []
with torch.no_grad():
    for i, (inputs, labels) in enumerate(test_dataloader):
        if i > 10:
            break
        # Move validation data to GPU as well
        for key in inputs:
            inputs[key] = inputs[key].to(DEVICE)
        
        labels = labels.squeeze(-1)
        labels = labels.to(DEVICE)

        logits = model(inputs)
        logits = logits.to(DEVICE)
        loss = criterion(logits, labels)
        val_loss += loss.item()

        probabilities = torch.softmax(logits, dim=1) # Apply softmax along the class dimension
        predictions = torch.argmax(probabilities, dim=1) # Get the index of the highest probability
        
        # Store labels and predictions
        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predictions.cpu().numpy())
avg_val_loss = val_loss / len(test_dataloader)
print(f"Validation Loss: {avg_test_loss:.4f}")


# Generate the classification report
# Convert lists to numpy arrays
y_true = np.array(all_labels)
y_pred = np.array(all_predictions)

print("\n--- Multiclass Classification Report ---")
print(classification_report(y_true, y_pred, target_names=['E', 'S', 'C', 'I']))

In [ ]:
# NDCG
# Convert label to relevance score and calculate NDCG
from sklearn.metrics import ndcg_score
import numpy as np

# Define mapping from label index to gain
label2gain = np.array([0, 0.01, 0.1, 1])  # I=0, C=1, S=2, E=3 (assuming label encoding order)

def labels_to_relevance(labels):
    # labels: tensor or numpy array of shape (batch,)
    return label2gain[labels.cpu().numpy()]

# Example: calculate NDCG for a batch (use after a batch in validation loop)
# Replace 'labels' and 'logits' with your actual batch variables
if 'labels' in locals() and 'logits' in locals():
    # Get predicted class indices
    pred_labels = logits.argmax(dim=1)
    # Convert to relevance scores
    true_relevance = labels_to_relevance(labels)
    pred_relevance = labels_to_relevance(pred_labels)
    # NDCG expects shape (1, n_samples)
    ndcg = ndcg_score(true_relevance.reshape(1, -1), pred_relevance.reshape(1, -1))
    print(f"NDCG for this batch: {ndcg:.4f}")
else:
    print("Run this cell after a batch to see NDCG.")